# Generated by Django 4.0.3 on 2022-04-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Questiontype',
        ),
    ]
