# Generated by Django 4.0.3 on 2022-04-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_question_id_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id_parent',
            new_name='QuestionType',
        ),
    ]
