# Generated by Django 4.0.3 on 2022-04-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_id_parent_question_questiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QuestionType',
            new_name='questionType',
        ),
    ]
